language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh install_github avantcredit/aws-tools
- ./travis-tool.sh install_deps
- ./travis-tool.sh install_r stringr
- ./travis-tool.sh install_r testthat
script: ./travis-tool.sh run_tests
after_failure:
- ./travis-tool.sh dump_logs
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: fVNqN6wg7L5siYy43erCQtz5r/pVhB6Il0U0cj9vvKth7tpfQWJLf8FMF/5xbRfDLIvcev0FyVAfpKGIRNPtt/8cXdwggoaQAYgUolSM4nvwYA/weO/fno6gdo/g0WthlCyZ4PClkGF8Cwlowgb7ctZ7SH1Xvn4bivI9yoP9POs=
    on_success: change
    on_failure: change
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}'
